#!/usr/bin/env python3

from Cheetah.Template import Template


# Static configuration
TEMPLATE_NAME = './template.tex'
FILLED_NAME = './filledTemplate.tex'

# Read template file
templateFile = open(TEMPLATE_NAME, 'r')
templateString = templateFile.read()
templateFile.close()

# Read data
# TODO
resumeData = [{'test' : 'test123'}];

# Fill template
template = Template(templateString, resumeData)
filledText = str(template)

# Write filled template
filledFile = open(FILLED_NAME, 'w')
filledFile.write(filledText)
filledFile.close()
